@CLIENT_URL=http://127.0.0.1:9090/clients/
@ROOM_URL=http://127.0.0.1:9090/rooms/ 

@RESERVATION_URL=http://127.0.0.1:9090/reservations/


#################################################################
### CLIENTS
#################################################################

### Get all clients
GET {{CLIENT_URL}}

### Create client
POST {{CLIENT_URL}}
Content-Type: application/json

{
  "name": "hassan",
  "email": "hassan@example.com",
  "phone": "0709876527",
  "address": "Agadir, Maroc"
}

### Delete client by ID
DELETE {{CLIENT_URL}}6


### Get client by ID
GET {{CLIENT_URL}}5

### modifier client by ID

PUT {{CLIENT_URL}}1
Content-Type: application/json

{
  "name": "Zakaria ",
  "email": "Zakaria@example.com",
  "phone": "0635946544",
  "address": "Fes, Maroc"
}


#################################################################
### ROOMS
#################################################################

### Get all rooms
GET {{ROOM_URL}}

### Create room
POST {{ROOM_URL}}
Content-Type: application/json

{
  "room_number": "203",
  "room_type": "suite",
  "price_per_night": 100.0
}

### Delete room by id
DELETE {{ROOM_URL}}6

### update room by ID
PUT {{ROOM_URL}}8
Content-Type: application/json

{
"room_number": "205",
"room_type": "double",
"price_per_night": 120.0
}


###Get rooms by price range
GET {{ROOM_URL}}price-range/?min_price=200&max_price=500

#################################################################
### RESERVATIONS
#################################################################

### Get all reservations
GET {{RESERVATION_URL}}

### Create reservation
POST {{RESERVATION_URL}}
Content-Type: application/json

{
  "client_id": 6,
  "room_id": 7,
  "check_in": "2026-01-05T14:00:00",
  "check_out": "2026-01-10T11:00:00"
}


###Get reservations by client ID
GET {{RESERVATION_URL}}client/2

###Cancel reservation by reservation ID and client ID
DELETE {{RESERVATION_URL}}4/client/3

###Check room availability
GET {{RESERVATION_URL}}check-availability/?room_id=1&check_in=2027-01-10T00:00:00&check_out=2027-01-12T00:00:00



@PLAT_URL=http://127.0.0.1:9090/plats/

#################################################################
### PLATS (RESTAURANT)
#################################################################

### Get all plats
GET {{PLAT_URL}}

### Create plat
POST {{PLAT_URL}}
Content-Type: application/json

{
  "nom_plat": "Pizza Margherita",
  "type_plat": "plat_principal",
  "prix_plat": 45.0,
  "ingredient_plat": "Tomate, fromage, basilic",
  "disponibilite": true
}

### Update plat
PUT {{PLAT_URL}}1
Content-Type: application/json

{
  "nom_plat": "Pizza 4 Fromages",
  "type_plat": "plat_principal",
  "prix_plat": 55.0,
  "ingredient_plat": "Mozzarella, gorgonzola, emmental, parmesan",
  "disponibilite": true
}

### Delete plat
DELETE {{PLAT_URL}}1
