@CLIENT_URL=http://127.0.0.1:9090/clients/
@ROOM_URL=http://127.0.0.1:9090/rooms/ 

@RESERVATION_URL=http://127.0.0.1:9090/reservations/


#################################################################
### CLIENTS
#################################################################

### Get all clients
GET {{CLIENT_URL}}

### Create client
POST {{CLIENT_URL}}
Content-Type: application/json

{
  "name": "hassan",
  "email": "hassan@example.com",
  "phone": "0709876527",
  "address": "Agadir, Maroc"
}

#################################################################
### ROOMS
#################################################################

### Get all rooms
GET {{ROOM_URL}}

### Create room
POST {{ROOM_URL}}
Content-Type: application/json

{
  "room_number": "203",
  "room_type": "suite",
  "price_per_night": 100.0
}

### Delete room by id
DELETE {{ROOM_URL}}6

#################################################################
### RESERVATIONS
#################################################################

### Get all reservations
GET {{RESERVATION_URL}}

### Create reservation
POST {{RESERVATION_URL}}
Content-Type: application/json

{
  "client_id": 6,
  "room_id": 7,
  "check_in": "2026-01-05T14:00:00",
  "check_out": "2026-01-10T11:00:00"
}

