export const roomData = [
  {
    id: 1,
    name: 'Superior Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 30,
    maxPerson: 1,
    price: 115,
    image: 'https://via.placeholder.com/300x200?text=Superior+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Superior+Room',
  },
  {
    id: 2,
    name: 'Signature Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 70,
    maxPerson: 2,
    price: 220,
    image: 'https://via.placeholder.com/300x200?text=Signature+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Signature+Room',
  },
  {
    id: 3,
    name: 'Deluxe Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 50,
    maxPerson: 3,
    price: 265,
    image: 'https://via.placeholder.com/300x200?text=Deluxe+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Deluxe+Room',
  },
  {
    id: 4,
    name: 'Luxury Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 50,
    maxPerson: 4,
    price: 289,
    image: 'https://via.placeholder.com/300x200?text=Luxury+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Luxury+Room',
  },
  {
    id: 5,
    name: 'Luxury Suite Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 90,
    maxPerson: 5,
    price: 320,
    image: 'https://via.placeholder.com/300x200?text=Luxury+Suite',
    imageLg: 'https://via.placeholder.com/600x400?text=Luxury+Suite',
  },
  {
    id: 6,
    name: 'Deluxe Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 45,
    maxPerson: 6,
    price: 344,
    image: 'https://via.placeholder.com/300x200?text=Deluxe+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Deluxe+Room',
  },
  {
    id: 7,
    name: 'Luxury Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 84,
    maxPerson: 7,
    price: 389,
    image: 'https://via.placeholder.com/300x200?text=Luxury+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Luxury+Room',
  },
  {
    id: 8,
    name: 'Deluxe Room',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit.Ea placeat eos sed voluptas unde veniam eligendi a. Quaerat molestiae hic omnis temporibus quos consequuntur nam voluptatum ea accusamus, corrupti nostrum eum placeat quibusdam quis beatae quae labore earum architecto aliquid debitis.',
    facilities: [
      { name: 'Wifi' },
      { name: 'Coffee' },
      { name: 'Bath' },
      { name: 'Parking Space' },
      { name: 'Swimming Pool' },
      { name: 'Breakfast' },
      { name: 'GYM' },
      { name: 'Drinks' },
    ],
    size: 48,
    maxPerson: 8,
    price: 499,
    image: 'https://via.placeholder.com/300x200?text=Deluxe+Room',
    imageLg: 'https://via.placeholder.com/600x400?text=Deluxe+Room',
  },
];
